title: nyu-dss/spackle
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  spackle is a wax theme for digital exhibits <br>from nyu special collections
baseurl: "/spackle" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
lang: en
incremental: true
sass:
   sourcemap: never

collections:
  bsd: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'bsd_item' # the layout for the pages to use
    metadata:
      source: 'bsd-data.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images' # path to the directory of images within `_data`
